using System;
using System.Threading.Tasks;
using JetBrains.Annotations;

namespace AD.Mathematics.Matrix
{
    /// <summary>
    /// Calculates the inverse of a square array with LU decomposition.
    /// </summary>
    [PublicAPI]
    public static class InversionLu
    {
        /// <summary>
        /// Calculates the inverse array.
        /// </summary>
        /// <param name="a">
        /// The array to invert.
        /// </param>
        /// <returns>
        /// The inverse of the array.
        /// </returns>
        [Pure]
        [NotNull]
        [ItemNotNull]
        public static double[][] InvertLu([NotNull][ItemNotNull] this double[][] a)
        {
            if (a is null)
            {
                throw new ArgumentNullException(nameof(a));
            }

            double[][] result = a.CloneArray();

            (double[][] lowerUpper, int[] permutation, int _) = a.DecomposeLu();

            for (int i = 0; i < a.Length; i++)
            {
                double[] b = new double[a.Length];

                for (int j = 0; j < permutation.Length; j++)
                {
                    b[j] = i == permutation[j] ? 1 : 0;
                }

                InversionHelper(lowerUpper, b);

                for (int j = 0; j < a.Length; j++)
                {
                    result[j][i] = b[j];
                }
            }

            return result;
        }

        /// <summary>
        /// Calculates the inverse array.
        /// </summary>
        /// <param name="a">
        /// The array to invert.
        /// </param>
        /// <param name="options">
        /// Options for running this method in parallel.
        /// </param>
        /// <returns>
        /// The inverse of the array.
        /// </returns>
        [Pure]
        [NotNull]
        [ItemNotNull]
        public static double[][] InvertLu([NotNull][ItemNotNull] this double[][] a, [NotNull] ParallelOptions options)
        {
            if (a is null)
            {
                throw new ArgumentNullException(nameof(a));
            }
            if (options is null)
            {
                throw new ArgumentNullException(nameof(options));
            }

            double[][] result = a.CloneArray(options);

            (double[][] lowerUpper, int[] permutation, int _) = a.DecomposeLu(options);

            Parallel.For(0, a.Length, options, i =>
            {
                double[] b = new double[a.Length];

                for (int j = 0; j < permutation.Length; j++)
                {
                    b[j] = i == permutation[j] ? 1 : 0;
                }

                InversionHelper(lowerUpper, b);

                for (int j = 0; j < a.Length; j++)
                {
                    result[j][i] = b[j];
                }
            });

            return result;
        }

        /// <summary>
        /// Helps to solve the regression equation.
        /// </summary>
        /// <param name="lowerUpper">
        /// The lower-upper decomposed matrix.
        /// </param>
        /// <param name="b">
        /// A vector permuted by the permutation array generated by the lower-upper decomposition.
        /// </param>
        /// <returns>
        /// An array.
        /// </returns>
        private static void InversionHelper([NotNull][ItemNotNull] this double[][] lowerUpper, [NotNull] double[] b)
        {
            if (lowerUpper is null)
            {
                throw new ArgumentNullException(nameof(lowerUpper));
            }
            if (b is null)
            {
                throw new ArgumentNullException(nameof(b));
            }

            for (int i = 1; i < lowerUpper.Length; i++)
            {
                b[i] -= b.DotProduct(lowerUpper[i], 0, i);
            }

            int index = lowerUpper.Length - 1;

            b[index] /= lowerUpper[index][index];

            for (int i = lowerUpper.Length - 2; i >= 0; i--)
            {
                b[i] -= b.DotProduct(lowerUpper[i], i + 1, lowerUpper.Length);

                b[i] /= lowerUpper[i][i];
            }
        }
    }
}